sonar.projectKey=distributed-log-monitoring
sonar.projectName=distributed-log-monitoring
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.git/**,**/node_modules/**